services:
#    xuru_dragon_versioning.example:
#        class: XuruDragon\VersioningBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    xuru_dragon_api_versioning.factory.changes_factory:
        class: XuruDragon\ApiVersioningBundle\Factory\ChangesFactory
        arguments: [ '@request_stack', '']

    xuru_dragon_api_versioning.event_listener.versioning_listener:
        class: XuruDragon\ApiVersioningBundle\EventListener\ApiVersioningListener
        arguments: ['@request_stack', '@xuru_dragon_api_versioning.factory.changes_factory', '']

